[Definition]
failregex = ^\[%(__date_ymd_hms)s\]\s+NOTICE\[\d+\]:\s+res_pjsip/pjsip_distributor\.c:\d+\s+log_failed_request:\s+Request\s+'.*'\s+from\s+'.*'\s+failed\s+for\s+'<HOST>:\d+'\s+\(callid:\s+.*\)\s+-\s+(?:Failed to authenticate|No matching endpoint found|Endpoint not found).*$
            ^\[%(__date_ymd_hms)s\]\s+NOTICE\[\d+\]:\s+res_pjsip/pjsip_distributor\.c:\d+\s+log_failed_request:\s+Request\s+'.*'\s+from\s+'.*'\s+failed\s+for\s+'<HOST>:\d+'\s+-\s+(?:Failed to authenticate|No matching endpoint found|Endpoint not found).*$
            ^\[%(__date_ymd_hms)s\]\s+SECURITY\[\d+\]:.*(?:InvalidPassword|ChallengeSent|FailedACL).*RemoteAddress="IPV[46]/(?:UDP|TCP|WS|WSS)/<HOST>/\d+".*$

ignoreregex =

[Init]
__date_ymd_hms = \d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}
