[Definition]
actionstart = iptables -N f2b-<name> 2>/dev/null || true
              iptables -C f2b-<name> -j RETURN 2>/dev/null || iptables -A f2b-<name> -j RETURN
              iptables -C DOCKER-USER -j f2b-<name> 2>/dev/null || iptables -I DOCKER-USER 1 -j f2b-<name>

actionstop = iptables -D DOCKER-USER -j f2b-<name> 2>/dev/null || true
             iptables -F f2b-<name> 2>/dev/null || true
             iptables -X f2b-<name> 2>/dev/null || true

actioncheck = iptables -n -L DOCKER-USER | grep -q 'f2b-<name>'

actionban = iptables -C f2b-<name> -s <ip> -j DROP 2>/dev/null || iptables -I f2b-<name> 1 -s <ip> -j DROP

actionunban = iptables -D f2b-<name> -s <ip> -j DROP 2>/dev/null || true

[Init]
