[asterisk-pjsip-auth]
enabled = true
filter = asterisk
logpath = /var/log/asterisk/messages
backend = auto
maxretry = 4
findtime = 10m
bantime = 24h
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 7d
action = iptables-docker[name=asterisk-pjsip-auth]

[asterisk-pjsip-malformed]
enabled = true
filter = asterisk-pjsip-malformed
logpath = /var/log/asterisk/messages
backend = auto
maxretry = 3
findtime = 10m
bantime = 24h
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 7d
action = iptables-docker[name=asterisk-pjsip-malformed]
