[asterisk-pjsip-auth]
enabled = true
filter = asterisk
logpath = /var/log/asterisk/messages
backend = auto
maxretry = 5
findtime = 10m
bantime = 12h
action = iptables-docker[name=asterisk-pjsip-auth]
