[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]

[webrtc]
exten => 1001,1,NoOp(WebRTC call to 1001)
 same => n,Set(DIAL_CONTACTS=${PJSIP_DIAL_CONTACTS(1001)})
 same => n,GotoIf($["${DIAL_CONTACTS}" = ""]?unavailable)
 same => n,Dial(${DIAL_CONTACTS},30)
 same => n,Hangup()
 same => n(unavailable),Playback(silence/1)
 same => n,Hangup()

exten => 1002,1,NoOp(WebRTC call to 1002)
 same => n,Set(DIAL_CONTACTS=${PJSIP_DIAL_CONTACTS(1002)})
 same => n,GotoIf($["${DIAL_CONTACTS}" = ""]?unavailable)
 same => n,Dial(${DIAL_CONTACTS},30)
 same => n,Hangup()
 same => n(unavailable),Playback(silence/1)
 same => n,Hangup()

exten => 2001,1,NoOp(Janus SIP call to 2001)
 same => n,Set(DIAL_CONTACTS=${PJSIP_DIAL_CONTACTS(2001)})
 same => n,GotoIf($["${DIAL_CONTACTS}" = ""]?unavailable)
 same => n,Dial(${DIAL_CONTACTS},30)
 same => n,Hangup()
 same => n(unavailable),Playback(silence/1)
 same => n,Hangup()

exten => 2002,1,NoOp(Janus SIP call to 2002)
 same => n,Set(DIAL_CONTACTS=${PJSIP_DIAL_CONTACTS(2002)})
 same => n,GotoIf($["${DIAL_CONTACTS}" = ""]?unavailable)
 same => n,Dial(${DIAL_CONTACTS},30)
 same => n,Hangup()
 same => n(unavailable),Playback(silence/1)
 same => n,Hangup()

exten => 600,1,NoOp(Echo test)
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()
