[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]

[webrtc]
exten => 1001,1,NoOp(WebRTC call to 1001)
 same => n,Dial(PJSIP/1001,30)
 same => n,Hangup()

exten => 1002,1,NoOp(WebRTC call to 1002)
 same => n,Dial(PJSIP/1002,30)
 same => n,Hangup()

exten => 600,1,NoOp(Echo test)
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()
