[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8088

tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile=/etc/letsencrypt/live/webrtc.sptm.online/fullchain.pem
tlsprivatekey=/etc/letsencrypt/live/webrtc.sptm.online/privkey.pem
