[modules]
autoload=yes
preload => res_http_websocket.so
preload => res_pjproject.so
preload => res_pjsip.so
load => res_pjsip_transport_websocket.so

noload => chan_alsa.so
noload => chan_mgcp.so
noload => chan_oss.so
noload => chan_sip.so
noload => chan_skinny.so
noload => chan_unistim.so
noload => bridge_native_rtp.so
noload => pbx_dundi.so
noload => res_hep_pjsip.so
noload => res_hep_rtcp.so
