[global]
type=global
user_agent=janus-softphone-asterisk

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=91.99.117.39
external_signaling_address=webrtc.sptm.online
local_net=172.16.0.0/12
local_net=192.168.0.0/16
local_net=10.0.0.0/8

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089
external_media_address=91.99.117.39
external_signaling_address=webrtc.sptm.online
local_net=172.16.0.0/12
local_net=192.168.0.0/16
local_net=10.0.0.0/8

[webrtc-endpoint](!)
type=endpoint
context=webrtc
transport=transport-wss
disallow=all
allow=opus
allow=ulaw
allow=alaw
webrtc=yes
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
ice_support=yes
media_use_received_transport=yes
rtcp_mux=yes
dtls_auto_generate_cert=yes
dtls_verify=fingerprint
dtls_setup=actpass
dtls_rekey=0
send_pai=yes
send_rpid=yes
trust_id_inbound=yes
trust_id_outbound=yes

[1001](webrtc-endpoint)
auth=1001
aors=1001
callerid=WebRTC 1001 <1001>

[1001]
type=auth
auth_type=userpass
username=1001
password=Webrtc1001!

[1001]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30

[1002](webrtc-endpoint)
auth=1002
aors=1002
callerid=WebRTC 1002 <1002>

[1002]
type=auth
auth_type=userpass
username=1002
password=Webrtc1002!

[1002]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30
